WIP onlykey-gpg runtime working with caveats
'onlykey-gpg init' failed with following stack trace. However, if you run
onlykey-gpg-agent first, then the init command works as expected.
Need to create a service for 'onlykey-gpg-agent'

Traceback (most recent call last):
  File "/gnu/store/589lmaqrpqz10yajg921vw8m4350ic67-python-onlykey-agent-1.1.12/bin/.onlykey-gpg-real", line 11, in <module>
    load_entry_point('onlykey-agent==1.1.12', 'console_scripts', 'onlykey-gpg')()
  File "/gnu/store/589lmaqrpqz10yajg921vw8m4350ic67-python-onlykey-agent-1.1.12/lib/python3.8/site-packages/onlykey_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/gnu/store/m62m132cc89zqz900qicxq180d2gdikf-python-lib-agent-1.0.3/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 385, in main
    return args.func(device_type=device_type, args=args)
  File "/gnu/store/m62m132cc89zqz900qicxq180d2gdikf-python-lib-agent-1.0.3/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 216, in run_init
    check_call(keyring.gpg_command(['--homedir', homedir, verbosity,
  File "/gnu/store/m62m132cc89zqz900qicxq180d2gdikf-python-lib-agent-1.0.3/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 114, in check_call
    subprocess.check_call(args=args, stdin=stdin, env=env)
  File "/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gnu/store/cc0r4spdjr25pisaj4fs7pcyb62v1r2x-gnupg-2.2.29/bin/gpg', '--homedir', '/home/antwane/.gnupg/onlykey', '--quiet', '--import', '/home/antwane/.gnupg/onlykey/pubkey.asc']' returned non-zero exit status 2.